# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/classification',
                'doc_host': 'https://fevzikilas.github.io',
                'git_url': 'https://github.com/fevzikilas/classification',
                'lib_path': 'classification'},
  'syms': {'classification.core': {'classification.core.foo': ('core.html#foo', 'classification/core.py')}}}
